### PR TITLE
New extension methods: exists() & find()

### PR DESCRIPTION
**Pull request by burak**

### CODE REVIEW

**Comment by tagomoris** [comment]
Hmm, now I don't use this library for my business.
@burak Do you have an interest to get maintenance bit for this?

**Comment by burak** [comment]
@tagomoris yes I can do that as we are actively using this module ( through the subclass Net::Hadoop::WebHDFS::LWP ).

In addition to Github, I will also need CPAN co-maint permission as well to be able to release the code.

**Comment by tagomoris** [comment]
I added you as a collaborator of this repository, and co-maint of Net::Hadoop::WebHDFS on CPAN.
Enjoy it! :)

**Comment by burak** [comment]
Cheers :)

**Pull request merged**
